### ISSUE TITLE
ConnectionRefusedError: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by v-ivanyshyn** [maxgerhardt/pio-swo-demo#3]
Following your instructions I met the error.
My environment: 
- Mac OS 13.4.1 (M1)
- Platformio Core 6.1.10 Home 3.4.4
- STM32F103 Custom board, stm32cube, stlink from China
Here is my platformio.ini file:
```
[env:stm32]
platform = ststm32
board = genericSTM32F103C8
framework = stm32cube
board_build.f_cpu = 72000000L

upload_protocol = stlink
debug_tool = stlink
monitor_speed = 115200

; add "Custom" -> "SWO Viewer" project task
extra_scripts = pre:add_swo_viewer.py
; set SWO trace clock in frequency to configured HCLK frequency
; in this example, board is clocked via HSI to 64MHz.
; if this number is wrong, there will be no output.
swo_trace_clkin_freq = 72000000 ;64000000
; if you want to see SWO outputs during debugging, a custom
; debug server invocation must be used.
; adapt interface and target accordingly.
; this entails changing the traceclk parameter to match
; the swo_trace_clkin_freq above.
; the SWO pin frequency param is irrelevant, since we are forwarding to
; tcl_trace, but OpenOCD will otherwise fail to enable the TPIU.
; this is used when starting debugging, not in the SWO Viewer task.
; after debugging starts, one must manually start the swo_viewer.py with
; python swo_parser.py --dont-run
debug_server = $PLATFORMIO_CORE_DIR/packages/tool-openocd/bin/openocd
  -f $PLATFORMIO_CORE_DIR/packages/tool-openocd/scripts/interface/stlink.cfg
  -f $PLATFORMIO_CORE_DIR/packages/tool-openocd/scripts/target/stm32f1x.cfg
  -c "tpiu create nucleo_f103rb.tpiu -dap nucleo_f103rb.dap -ap-num 0"
  -c "nucleo_f103rb.tpiu configure -protocol uart"
  -c "nucleo_f103rb.tpiu configure -output -"
  -c "nucleo_f103rb.tpiu configure -traceclk 72000000"
  -c "nucleo_f103rb.tpiu configure -pin-freq 2000000"
  -c "nucleo_f103rb.tpiu configure -formatter 0"
  -c "itm ports on"
  -c "nucleo_f103rb.tpiu enable"
  -c "tcl_port 6666"
```

And the console log:
```
 *  Executing task: platformio run --target swo_viewer --environment stm32 

Warning! Ignore unknown configuration option `swo_trace_clkin_freq` in section [env:stm32]
Processing stm32 (platform: ststm32; board: genericSTM32F103C8; framework: stm32cube)
---------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/genericSTM32F103C8.html
PLATFORM: ST STM32 (15.4.1) > STM32F103C8 (20k RAM. 64k Flash)
HARDWARE: STM32F103C8T6 72MHz, 20KB RAM, 64KB Flash
DEBUG: Current (stlink) External (blackmagic, cmsis-dap, jlink, stlink)
PACKAGES: 
 - framework-stm32cubef1 @ 1.8.4 
 - tool-ldscripts-ststm32 @ 0.2.0 
 - toolchain-gccarmnoneeabi @ 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 32 compatible libraries
Scanning dependencies...
Dependency Graph
Building in release mode
swo_viewer_task(["swo_viewer"], [])
Entrypoint
Starting OpenOCD with SWO Trace clock-in frequency 72000000, SWO trace frequency 115200. Invocation:
['/Users/me/.platformio/packages/tool-openocd/bin/openocd', '-s', '/Users/me/.platformio/packages/tool-openocd/scripts', '-f', 'interface/stlink.cfg', '-c', 'transport select hla_swd', '-f', 'target/stm32f1x.cfg', '-c', 'init; tpiu config internal - uart false 72000000 115200; itm ports on']
xPack OpenOCD x86_64 Open On-Chip Debugger 0.11.0+dev (2021-10-17-00:18)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : DEPRECATED target event trace-config; use TPIU events {pre,post}-{enable,disable}
Info : clock speed 1000 kHz
Info : STLINK V2J29S7 (API v2) VID:PID 0483:3748
Info : Target voltage: 3.132124
Traceback (most recent call last):
  File "/project/swo_parser.py", line 198, in <module>
    swo_parser_main()
  File "/project/swo_parser.py", line 145, in swo_parser_main
    tcl_socket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 61] Connection refused
Info : stm32f1x.cpu: Cortex-M3 r1p1 processor detected
Info : stm32f1x.cpu: target has 6 breakpoints, 4 watchpoints
Info : starting gdb server for stm32f1x.cpu on 3333
Info : Listening on port 3333 for gdb connections
Info : DEPRECATED 'tpiu config' command: Adding a TPIU 'stm32f1x.cpu.tpiu' in the configuration
Info : DEPRECATED 'tpiu config' command: Running: 'tpiu create stm32f1x.cpu.tpiu -dap stm32f1x.dap -ap-num 0'
Info : DEPRECATED 'tpiu config' command: Running: 'stm32f1x.cpu.tpiu configure -protocol uart -traceclk 72000000 -pin-freq 115200 -output - -formatter false'
Info : DEPRECATED 'tpiu config' command: Running: 'stm32f1x.cpu.tpiu enable'
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections

```

**Comment by maxgerhardt** [comment]
in

https://github.com/maxgerhardt/pio-swo-demo/blob/f94a936d3c67f0c2f2eaef62c1dd9707c58f99c4/swo_parser.py#L139-L143

can you modify this too
```python
def swo_parser_main():
    time.sleep(3)
    # Set up the socket to the OpenOCD Tcl server
    HOST = 'localhost'
    PORT = 6666
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as tcl_socket:
```
?

**Comment by v-ivanyshyn** [comment]
Yes, "time.sleep(3)" fixed the issue. Thanks!

**Comment by cocodmdr** [comment]
it solves the error but then I don't see the data. I did ctrl-c and then the data appeared : 
```
Warning! Ignore unknown configuration option `swo_trace_clkin_freq` in section [env:blackpill_f401cc]
Processing blackpill_f401cc (platform: ststm32; board: blackpill_f401cc; framework: stm32cube)
-------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/ststm32/blackpill_f401cc.html
PLATFORM: ST STM32 (16.1.0) > WeAct Studio BlackPill V2.0 (STM32F401CC)
HARDWARE: STM32F401CCU6 84MHz, 64KB RAM, 256KB Flash
DEBUG: Current (stlink) External (blackmagic, cmsis-dap, jlink, stlink)
PACKAGES: 
 - framework-stm32cubef4 @ 1.26.2 
 - tool-ldscripts-ststm32 @ 0.2.0 
 - toolchain-gccarmnoneeabi @ 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 52 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
swo_viewer_task(["swo_viewer"], [])
Entrypoint
Starting OpenOCD with SWO Trace clock-in frequency 84000000, SWO trace frequency 115200. Invocation:
['/home/corentin/.platformio/packages/tool-openocd/bin/openocd', '-s', '/home/corentin/.platformio/packages/tool-openocd/scripts', '-f', 'interface/stlink.cfg', '-c', 'transport select hla_swd', '-f', 'target/stm32f4x.cfg', '-c', 'init; tpiu config internal - uart false 84000000 115200; itm ports on']
xPack Open On-Chip Debugger 0.12.0-01004-g9ea7f3d64-dirty (2023-01-30-15:03)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 2000 kHz
Info : STLINK V2J29S7 (API v2) VID:PID 0483:3748
Info : Target voltage: 3.151453
Info : [stm32f4x.cpu] Cortex-M4 r0p1 processor detected
Info : [stm32f4x.cpu] target has 6 breakpoints, 4 watchpoints
Info : starting gdb server for stm32f4x.cpu on 3333
Info : Listening on port 3333 for gdb connections
Info : DEPRECATED 'tpiu config' command: Using stm32f4x.tpiu
Info : DEPRECATED 'tpiu config' command: Running: 'stm32f4x.tpiu configure -protocol uart -traceclk 84000000 -pin-freq 115200 -output - -formatter false'
Info : DEPRECATED 'tpiu config' command: Running: 'stm32f4x.tpiu enable'
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : accepting 'tcl' connection on tcp/6666
Info : Target trace output  is enabled
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
^Cshutdown command invoked
Exited from TCL client
*** [swo_viewer] Build interrupted.
SWO client successfully connected to OpenOCD on localhost:6666
[Stream ID 0] SWO test firmware start!
[Stream ID 0] Blinky number 0!
[Stream ID 0] Blinky number 1!
[Stream ID 0] Blinky number 2!
[Stream ID 0] Blinky number 3!
[Stream ID 0] Blinky number 4!
[Stream ID 0] Blinky number 5!
[Stream ID 0] Blinky number 6!
[Stream ID 0] Blinky number 7!
[Stream ID 0] Blinky number 8!
[Stream ID 0] Blinky number 9!
[Stream ID 0] Blinky number 10!
[Stream ID 0] Blinky number 11!
[Stream ID 0] Blinky number 12!
[Stream ID 0] Blinky number 13!
[Stream ID 0] Blinky number 14!
[Stream ID 0] Blinky number 15!
[Stream ID 0] Blinky number 16!
[Stream ID 0] Blinky number 17!
[Stream ID 0] Blinky number 18!
[Stream ID 0] Blinky number 19!
[Stream ID 0] Blinky number 20!
[Stream ID 0] Blinky number 21!
[Stream ID 0] Blinky number 22!
[Stream ID 0] Blinky number 23!
[Stream ID 0] Blinky number 24!
[Stream ID 0] Blinky number 25!
[Stream ID 0] Blinky number 26!
[Stream ID 0] Blinky number 27!
[Stream ID 0] Blinky number 28!
[Stream ID 0] Blinky number 29!
[Stream ID 0] Blinky number 30!
[Stream ID 0] Blinky number 31!
[Stream ID 0] Blinky number 32!
[Stream ID 0] Blinky number 33!
[Stream ID 0] Blinky number 34!
[Stream ID 0] Blinky number 35!
[Stream ID 0] Blinky number 36!
[Stream ID 0] Blinky number 37!
[Stream ID 0] Blinky number 38!
[Stream ID 0] Blinky number 39!
[Stream ID 0] Blinky number 40!
[Stream ID 0] Blinky number 41!
[Stream ID 0] Blinky number 42!
[Stream ID 0] Blinky number 43!
[Stream ID 0] Blinky number 44!
[Stream ID 0] Blinky number 45!
[Stream ID 0] Blinky number 46!
[Stream ID 0] Blinky number 47!
[Stream ID 0] Blinky number 48!
[Stream ID 0] Blinky number 49!
[Stream ID 0] Blinky number 50!
[Stream ID 0] Blinky number 51!
[Stream ID 0] Blinky number 52!
[Stream ID 0] Blinky number 53!
[Stream ID 0] Blinky number 54!
[Stream ID 0] Blinky number 55!
[Stream ID 0] Blinky number 56!
[Stream ID 0] Blinky number 57!
[Stream ID 0] Blinky number 58!
[Stream ID 0] Blinky number 59!
[Stream ID 0] Blinky number 60!
[Stream ID 0] Blinky number 61!
[Stream ID 0] Blinky number 62!
[Stream ID 0] Blinky number 63!
[Stream ID 0] Blinky number 64!
[Stream ID 0] Blinky number 65!
[Stream ID 0] Blinky number 66!
[Stream ID 0] Blinky number 67!
[Stream ID 0] Blinky number 68!
[Stream ID 0] Blinky number 69!
[Stream ID 0] Blinky number 70!
[Stream ID 0] Blinky number 71!
[Stream ID 0] Blinky number 72!
[Stream ID 0] Blinky number 73!
[Stream ID 0] Blinky number 74!
[Stream ID 0] Blinky number 75!
[Stream ID 0] Blinky number 76!
[Stream ID 0] Blinky number 77!
[Stream ID 0] Blinky number 78!
[Stream ID 0] Blinky number 79!
[Stream ID 0] Blinky number 80!
[Stream ID 0] Blinky number 81!
[Stream ID 0] Blinky number 82!
[Stream ID 0] Blinky number 83!
[Stream ID 0] Blinky number 84!
[Stream ID 0] Blinky number 85!
[Stream ID 0] Blinky number 86!
[Stream ID 0] Blinky number 87!
[Stream ID 0] Blinky number 88!
[Stream ID 0] Blinky number 89!
[Stream ID 0] Blinky number 90!
[Stream ID 0] Blinky number 91!
[Stream ID 0] Blinky number 92!
[Stream ID 0] Blinky number 93!
[Stream ID 0] Blinky number 94!
[Stream ID 0] Blinky number 95!
[Stream ID 0] Blinky number 96!
[Stream ID 0] Blinky number 97!
[Stream ID 0] Blinky number 98!
[Stream ID 0] Blinky number 99!
[Stream ID 0] Blinky number 100!
[Stream ID 0] Blinky number 101!
[Stream ID 0] Blinky number 102!
[Stream ID 0] Blinky number 103!
[Stream ID 0] Blinky number 104!
[Stream ID 0] Blinky number 105!
[Stream ID 0] Blinky number 106!
[Stream ID 0] Blinky number 107!
[Stream ID 0] Blinky number 108!
[Stream ID 0] Blinky number 109!
[Stream ID 0] Blinky number 110!
[Stream ID 0] Blinky number 111!
[Stream ID 0] Blinky number 112!
[Stream ID 0] Blinky number 113!
[Stream ID 0] Blinky number 114!
[Stream ID 0] Blinky number 115!
[Stream ID 0] Blinky number 116!
[Stream ID 0] Blinky number 117!
[Stream ID 0] Blinky number 118!
[Stream ID 0] Blinky number 119!
[Stream ID 0] Blinky number 120!
[Stream ID 0] Blinky number 121!
[Stream ID 0] Blinky number 122!
[Stream ID 0] Blinky number 123!
[Stream ID 0] Blinky number 124!
[Stream ID 0] Blinky number 125!
[Stream ID 0] Blinky number 126!
[Stream ID 0] Blinky number 127!
[Stream ID 0] Blinky number 128!
[Stream ID 0] Blinky number 129!
[Stream ID 0] Blinky number 130!
==== Terminating SWO / TCL client program ====
AbortedByUser: Aborted by user
```

**Comment by maxgerhardt** [comment]
Then there's a problem with flushing the pipe or PIO core behavior has changed. Can you try and export `PYTHONUNBUFFERED` with value `1` as a global environment variable in your user profile? 

Yuu can also try and modify this line

https://github.com/maxgerhardt/pio-swo-demo/blob/f94a936d3c67f0c2f2eaef62c1dd9707c58f99c4/add_swo_viewer.py#L47

to add `env = {"PYTHONUNBUFFERED": "1"}` as an additional argument (see [docs](https://docs.python.org/3/library/subprocess.html#popen-constructor))

**Comment by cocodmdr** [comment]
I did not manage to do exactly what you suggested but with this it works: 

I added this line at the beggining of the function `def swo_viewer_task(*args, **kwargs):`
```
os.environ['PYTHONUNBUFFERED'] = '1'
``` 

Thank you for your help ! Should I make a merge request for this problem ?

**Comment by maxgerhardt** [comment]
Sure, that'd be great.
