### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by cocodmdr** [maxgerhardt/pio-swo-demo#5]
I am able to upload the code and see the printf in the terminal but I am not able to debug.

In platformio.ini I modified these lines to match the board I am using : blackpill_f401cc
The debugging session does not start, only the project builds and then nothing happens.
However if I comment these lines then it debugs fine, but I cannot see the printf.

How should I modify this for my board ?
```
debug_server = $PLATFORMIO_CORE_DIR/packages/tool-openocd/bin/openocd
  -f $PLATFORMIO_CORE_DIR/packages/tool-openocd/scripts/interface/stlink.cfg
  -f $PLATFORMIO_CORE_DIR/packages/tool-openocd/scripts/target/stm32f4x.cfg
  -c "tpiu create blackpill_f401cc.tpiu -dap blackpill_f401cc.dap -ap-num 0"
  -c "blackpill_f401cc.tpiu configure -protocol uart"
  -c "blackpill_f401cc.tpiu configure -output -"
  -c "blackpill_f401cc.tpiu configure -traceclk 84000000"
  -c "blackpill_f401cc.tpiu configure -pin-freq 2000000"
  -c "blackpill_f401cc.tpiu configure -formatter 0"
  -c "itm ports on"
  -c "blackpill_f401cc.tpiu enable"
  -c "tcl_port 6666"
```

when I try to run `$ python swo_parser.py --dont-run`
then I get 
```
Traceback (most recent call last):
  File "/home/corentin/Documents/PlatformIO/Projects/blackpill_f401cc_blinky/swo_parser.py", line 199, in <module>
    swo_parser_main()
  File "/home/corentin/Documents/PlatformIO/Projects/blackpill_f401cc_blinky/swo_parser.py", line 146, in swo_parser_main
    tcl_socket.connect((HOST, PORT))
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by maxgerhardt** [comment]
I think with the st-link and SWD protocol you explicitly have to select SWD protocol.

```ini
debug_server = $PLATFORMIO_CORE_DIR/packages/tool-openocd/bin/openocd
  -f $PLATFORMIO_CORE_DIR/packages/tool-openocd/scripts/interface/stlink.cfg
  -c "transport select hla_swd"
  -f $PLATFORMIO_CORE_DIR/packages/tool-openocd/scripts/target/stm32f4x.cfg
  -c "tpiu create blackpill_f401cc.tpiu -dap blackpill_f401cc.dap -ap-num 0"
  -c "blackpill_f401cc.tpiu configure -protocol uart"
  -c "blackpill_f401cc.tpiu configure -output -"
  -c "blackpill_f401cc.tpiu configure -traceclk 84000000"
  -c "blackpill_f401cc.tpiu configure -pin-freq 2000000"
  -c "blackpill_f401cc.tpiu configure -formatter 0"
  -c "itm ports on"
  -c "blackpill_f401cc.tpiu enable"
  -c "tcl_port 6666"
```
You can also try and evaluate the command stand-alone in a terminal  session (but with paths properly substituted) to see what it gives. Maybe there are errors in the "Debug Console" tab?

**Comment by cocodmdr** [comment]
yes my bad there are errors in the debug console that I didn't see: 
```
undefinedWarning! Ignore unknown configuration option `swo_trace_clkin_freq` in section [env:blackpill_f401cc]
Reading symbols from /home/corentin/Documents/PlatformIO/Projects/blackpill_f401cc_blinky/.pio/build/blackpill_f401cc/firmware.elf...
done.
PlatformIO Unified Debugger -> https://bit.ly/pio-debug
PlatformIO: debug_tool = stlink
PlatformIO: Initializing remote target...
xPack Open On-Chip Debugger 0.12.0-01004-g9ea7f3d64-dirty (2023-01-30-15:03)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
embedded:startup.tcl:28: Error: Can't find /home/corentin/.platformio/packages/tool-openocd/scripts/interface/stlink.cfg
in procedure 'script' 
at file "embedded:startup.tcl", line 28
.pioinit:13: Error in sourced command file:
Remote communication error.  Target disconnected.: Connection reset by peer.
```
Should I provide stlink.cfg or should it be there by default from platformio ?

**Comment by maxgerhardt** [comment]
>/home/corentin/.platformio/packages/tool-openocd/scripts/interface/stlink.cfg

I don't think this is the right path, look for yourself in `/home/corentin/.platformio/packages/tool-openocd`. On Windows at least, the subfolder is `tool-openocd\openocd\scripts`, not `tool-openocd\scripts`. It may also be advantageous to set that as the script directory with `-s` so that all `-f` paths can be shortened.

```ini
debug_server = $PLATFORMIO_CORE_DIR/packages/tool-openocd/bin/openocd
  -s $PLATFORMIO_CORE_DIR/packages/tool-openocd/openocd/scripts/
  -f interface/stlink.cfg
  -c "transport select hla_swd"
  -f target/stm32f4x.cfg
  -c "tpiu create blackpill_f401cc.tpiu -dap blackpill_f401cc.dap -ap-num 0"
  -c "blackpill_f401cc.tpiu configure -protocol uart"
  -c "blackpill_f401cc.tpiu configure -output -"
  -c "blackpill_f401cc.tpiu configure -traceclk 84000000"
  -c "blackpill_f401cc.tpiu configure -pin-freq 2000000"
  -c "blackpill_f401cc.tpiu configure -formatter 0"
  -c "itm ports on"
  -c "blackpill_f401cc.tpiu enable"
  -c "tcl_port 6666"
```

**Comment by cocodmdr** [comment]
Seems to resolve the problem but now I have an other one:
```
undefinedWarning! Ignore unknown configuration option `swo_trace_clkin_freq` in section [env:blackpill_f401cc]
Reading symbols from /home/corentin/Documents/PlatformIO/Projects/blackpill_f401cc_blinky/.pio/build/blackpill_f401cc/firmware.elf...
done.
PlatformIO Unified Debugger -> https://bit.ly/pio-debug
PlatformIO: debug_tool = stlink
PlatformIO: Initializing remote target...
xPack Open On-Chip Debugger 0.12.0-01004-g9ea7f3d64-dirty (2023-01-30-15:03)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
DAP name invalid!
.pioinit:13: Error in sourced command file:
Remote communication error.  Target disconnected.: Connection reset by peer.
```
Sorry to bother you that much !

**Comment by maxgerhardt** [comment]
I'm not sure on this one, but then the referenced `-dap` argument is wrong. Looking at https://github.com/openocd-org/openocd/blob/master/tcl/target/stm32f4x.cfg#L11-L41 the default name is `stm32f4x.dap`, not `blackpill_f401cc.dap`, so try that. 

Though I wonder how the ` -dap nucleo_f103rb.dap` is correct in this repo too, or maybe it worked in an older OpenOCD version.

**Comment by maxgerhardt** [comment]
Maybe it must also just be the environment name, `blackpill_f401cc_blinky.dap`.

**Comment by cocodmdr** [comment]
yes it helps, thanks ! I now have: 
```
undefinedWarning! Ignore unknown configuration option `swo_trace_clkin_freq` in section [env:blackpill_f401cc]
Reading symbols from /home/corentin/Documents/PlatformIO/Projects/blackpill_f401cc_blinky/.pio/build/blackpill_f401cc/firmware.elf...
done.
PlatformIO Unified Debugger -> https://bit.ly/pio-debug
PlatformIO: debug_tool = stlink
PlatformIO: Initializing remote target...
xPack Open On-Chip Debugger 0.12.0-01004-g9ea7f3d64-dirty (2023-01-30-15:03)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
hla_swd
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
cannot create TPIU object because a command with name 'stm32f4x.tpiu' already exists
.pioinit:13: Error in sourced command file:
Remote communication error.  Target disconnected.: Connection reset by peer.
```

So then I commented out that line `  -c "tpiu create blackpill_f401cc.tpiu -dap blackpill_f401cc.dap -ap-num 0"`
And now it starts the debuging ! Let's hope I can see the printf !

**Comment by cocodmdr** [comment]
Yes ! I can debug and see the printf ! 
my config looks now like that:
```
debug_server = $PLATFORMIO_CORE_DIR/packages/tool-openocd/bin/openocd
  -s $PLATFORMIO_CORE_DIR/packages/tool-openocd/openocd/scripts/
  -f interface/stlink.cfg
  -c "transport select hla_swd"
  -f  target/stm32f4x.cfg
  ; -c "tpiu create stm32f4x.tpiu -dap stm32f4x.dap -ap-num 0"
  -c "stm32f4x.tpiu configure -protocol uart"
  -c "stm32f4x.tpiu configure -output -"
  -c "stm32f4x.tpiu configure -traceclk 84000000"
  -c "stm32f4x.tpiu configure -pin-freq 2000000"
  -c "stm32f4x.tpiu configure -formatter 0"
  -c "itm ports on"
  -c "stm32f4x.tpiu enable"
  -c "tcl_port 6666"
```

**Comment by cocodmdr** [comment]
Should I make a MR to correct the path to the stlink.cfg, add swd as the transport, and add in the readme how to change it to a stm32f4x based board ?

**Comment by cocodmdr** [comment]
> Maybe it must also just be the environment name, `blackpill_f401cc_blinky.dap`.

No I tried and it did not help.

**Comment by maxgerhardt** [comment]
We can definitely merge a change in that adds another `[env:xyz]` in the platformio.ini (and adapt the `main.c` based on identification macros to include the right HAL), but regardless I have to check if the nucleo environment is now broken as-is.
